config/routes.rb
Brodwubz::Application.routes.draw do
  devise_for :users

  get 'wublist', to: 'wub#index', as: :wublist

  get 'newwub', to: 'wub#create', as: :create_wub
  get 'wub/:wub_id/deletetrack/:track_id', to: 'wub#deletetrack', as: :delete_track
  match 'wub/:id/addtrack', to: 'wub#addtrack', as: :add_track, via: [:get, :post]
  get 'wub/:id', to: 'wub#show', as: :wub

  get 'my-instruments', to: 'instrument#index', as: :my_instruments
  get 'instrument/edit/:id', to: 'instrument#edit', as: :instrument
  get 'instrument/delete/:id', to: 'instrument#delete', as: :delete_instrument

  root 'pages#home'

end

app/models/instrument.rb
class Instrument < ActiveRecord::Base
  has_many :tracks, dependent: :destroy
  validates :name, presence: true
  validate :oscillation_config_valid

  def load_defaults
    self.name = 'New Instrument'
    self.instrument_type = 'sine'
    self.frequency = 400
    self.envelope = set_envelope_using_obj([
      { :f => 'set', :v => 0.01, :t => 0 },
      { :f => 'exponential', :v => 1, :t => 0.1 },
      { :f => 'exponential', :v => 0.1, :t => 0.6 },
      { :f => 'linear', :v => 0, :t => 0.7 }
    ])
  end

  def oscillation_config_valid
    if instrument_type == 'sine' or instrument_type == 'square' or instrument_type == 'sawtooth' or instrument_type == 'triangle'
      # validate oscillator

      errors.add(:frequency, 'Frequency must be an integer') unless frequency.is_a? Integer

      env_obj = parsed_envelope
      if env_obj.is_a? Array
        previous_time = -1
        env_obj.each do |item|
          f = item['f']
          v = item['v']
          t = item['t']
          errors.add(:envelope, "Invalid ramp type: #{f}") unless f == 'set' or f == 'linear' or f == 'exponential'
          errors.add(:envelope, 'Invalid gain: #{v}, must be between 0 and 1') unless (v.is_a? Integer or v.is_a? Float) and v >= 0 and v <= 1
          errors.add(:envelope, 'Invalid time: #{t}, must be greater than 0 and the previous time') unless (t.is_a? Integer or t.is_a? Float) and t >= 0 and t > previous_time
          previous_time = t || 0
          # cannot go to 0 using exponential ramp - API cannot hack it
          errors.add(:envelope, 'Cannot ramp to #{v} when using exponential ramp') if v == 0 and f == 'exponential'
        end
      else
        errors.add(:envelope, 'Envelope was not parsed into an array')
      end
    else
      errors.add(:instrument_type, 'Invalid waveform')
    end
  end

  def set_envelope_using_obj(obj)
    self.envelope = JSON.generate(obj)
  end

  def parsed_envelope
    JSON.parse(self.envelope)
  end
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :wub
  belongs_to :instrument
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/wub.rb
class Wub < ActiveRecord::Base
  has_many :tracks, dependent: :destroy

  def to_json(some_stuff)
    Jbuilder.encode do |json|
      json.wub_id self.id
      json.name self.name
      json.owner User.find(self.owner_id)
      json.bpm self.bpm
      json.numBeatsPerBar self.num_beats_per_bar
      json.numBars self.num_bars

      json.tracks self.tracks do |track|
        json.track_id track.id
        json.name track.name
        json.beats track.beats
        json.creator User.find(track.creator_id)
        json.instrument_type track.instrument.instrument_type
        json.frequency track.instrument.frequency
        json.envelope track.instrument.parsed_envelope
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from ActiveRecord::RecordNotFound, :with => :four_oh_four if Rails.env.production?

  def four_oh_four
    respond_to do |type|
      type.html { render :template => "errors/error_404", :status => 404 }
      type.all  { render :nothing => true, :status => 404 }
    end
    true
  end
end

app/controllers/instrument_controller.rb
class InstrumentController < ApplicationController
  before_action :authenticate_user!

  def index
    # list instruments you have made
    @instruments = Instrument.where(:creator_id => current_user.id)
  end

  def edit
    @instrument = Instrument.find(params.require(:id))
=begin
    #TODO: move both edit & create forms to this one controller method
    #wub#addtrack will just creatinst = Instrument.new do |i|
        i.name = params.require(:name)
        i.creator_id = current_user.id
        i.instrument_type = params.require(:waveform)
        i.frequency = params.require(:frequency).to_i
        envobj = []
        params.require(:env_node_count).to_i.times do |iter|
          envobj.push({
            :f => params.require(:env_gain_ramp)[iter],
            :v => params.require(:env_gain)[iter].to_f,
            :t => params.require(:env_time)[iter].to_f
          })
        end
        i.set_envelope_using_obj(envobj)
        i.save
      end
      # no errors? add track
      if inst.errors.size == 0
        new_instrument_id = inst.id
      else
        @errors = inst.errors
      end
=end
  end

  def delete
    Instrument.where(:creator_id => current_user.id).find(params.require(:id)).destroy
    redirect_to my_instruments_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/wub_controller.rb
class WubController < ApplicationController
  before_action :authenticate_user!

  def create
    wub = Wub.new do |w|
      w.name = 'Wubway Sandwich'
      w.owner_id = current_user.id
      w.num_beats_per_bar = 4
      w.num_bars = 4
      w.bpm = 120
      w.save
    end
    redirect_to wub_path(wub)
  end

  def index
    # list all of your own wubs
    @wubs = Wub.where(owner_id: current_user.id)
  end

  def show
    @wub = Wub.find(params.require(:id))
    respond_to do |format|
      format.html
      format.json { render json: @wub }
    end
  end

  def addtrack
    @wub = Wub.find(params.require(:id))
    @instruments = Instrument.all
    
    if params.has_key? :existing or params.has_key? :new
      @track = Track.new do |t|
        t.creator_id = current_user.id
        t.wub_id = @wub.id
        t.name = 'New track'
        t.beats = ''
      end

      if params.has_key? :new
        @inst = Instrument.new
        @inst.load_defaults
        @inst.creator_id = current_user.id
        @inst.save
        @track.instrument_id = @inst.id
        @track.save
        redirect_to edit_instrument_path(@inst)
      elsif params.has_key? :existing
        @track.instrument_id = params.require(:existing_instrument).to_i
        @track.save
        redirect_to wub_path(@wub)
      end
    end
  end

  def deletetrack
    # permissionslol
    @wub = Wub.find(params.require(:wub_id))
    @track = Track.find(params.require(:track_id))
    @track.delete
    redirect_to wub_path(@wub)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instrument_helper.rb
module InstrumentHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/wub_helper.rb
module WubHelper
end

app/views/instrument/edit.html.erb
<% if !@errors.nil? and @errors.any? %>
  <ul class="errors">
    <% @errors.full_messages.each do |e| %>
      <li><%= e %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @instrument do |f| %>
<div>
  <div>
    <label>Name</label>
    <%= f.text_field :name %>
  </div>

  <div>
    <label>Waveform:</label>
    <%= f.select(:instrument_type, ['sine', 'square', 'sawtooth', 'triangle']) %>
  </div>

  <div>
    <label>Frequency</label>
    <%= f.text_field :frequency %>
  </div>

  <div>
    <label>Envelope node count</label>
    <%= text_field_tag :env_node_count, 4 %>
  </div>

  <p>Times are in seconds. Gain is from 0-1.</p>
  <div id="envelope_nodes"></div>
</div>

<div>
  <%= f.submit 'Save' %>
</div>
<% end %>

app/views/instrument/index.html.erb
<h1>Your instruments</h1>

<ul>
  <% @instruments.each do |i| %>
    <li><%= i.name %> | <%= link_to "Edit", edit_instrument_path(i) %> | <%= link_to "Delete", delete_instrument_path(i) %></li>
  <% end %>
</ul>

<p><%= link_to 'My wubs', wublist_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Brodwubz</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/pages/home.html.erb
<h1>LOLOLOLOLOLO<a href="/wublist/">LOGIN</a></h1>


<p>&copy; all shites reserved by Willbo Brodfucker. So fuck you.</p>

app/views/wub/addtrack.html.erb
<h1>Back to <%= link_to @wub.name, wub_path(@wub) %></h1>

<%= form_tag do %>
<div>
  <label>Use existing instrument:</label>
  <select name="existing_instrument">
    <% @instruments.each do |i| %>
      <option value="<%= i.id %>"><%= i.name %></option>
    <% end %>
  </select>
  <input name="existing" type="submit" value="Use"/>
</div>

<div>
  Or <input name="new" type="submit" value="create a new one"/>.
</div>
<% end %>

app/views/wub/index.html.erb
<h1>These are your wubs:</h1>

<% if @wubs.count == 0 %>
  <p>Hold on m8... You have no wubs. What even the fuck are you?</p>
  <p>Get somebody to invite you to their hot wet shit, or <%= link_to 'make one of your own', create_wub_path %>.</p>
<% else %>
  <ul>
    <% @wubs.each do |wub| %>
      <li><%= link_to "#{wub.id}: #{wub.name}", wub_path(wub) %></li>
    <% end %>
  </ul>
  <p>Or, <%= link_to 'make some more audiojizz', create_wub_path %>.</p>
<% end %>

<p>
<%= link_to 'My instruments', my_instruments_path %>
</p>

app/views/wub/show.html.erb
<%= link_to '&laquo; Back to wubs'.html_safe, wublist_path %>
<h1 id="wubname"><%= @wub.name %></h1>

<div class="controls">
  <button id="play">Play</button>
      
  Beats per bar:
  <select id="beatsperbar">
    <option>3</option>
    <option>4</option>
    <option>5</option>
    <option>6</option>
    <option>7</option>
  </select>
      
  Bars:
  <select id="numbars">
    <option>1</option>
    <option>2</option>
    <option>3</option>
    <option>4</option>
  </select>
      
  BPM:
  <select id="bpm">
    <option>60</option>
    <option>80</option>
    <option>100</option>
    <option>120</option>
    <option>140</option>
    <option>180</option>
    <option>200</option>
    <option>240</option>
    <option>280</option>
  </select>
</div>
    
    
<div id="tracker"></div>
    
<ul id="tracks"></ul>
<p><a id="new-track" href="<%= add_track_path(@wub) %>">Add Track</a></p>
    
<script>
$(function(){
    wubmachine.load_wub(<%= @wub.id %>);
});
</script>
    
<h6>Helpful links:</h6>
<p><a target="_blank" href="http://www.html5rocks.com/en/tutorials/webaudio/intro/">http://www.html5rocks.com/en/tutorials/webaudio/intro/</a></p>
<p><a target="_blank" href="http://blog.teamtreehouse.com/building-a-synthesizer-with-the-web-audio-api">http://blog.teamtreehouse.com/building-a-synthesizer-with-the-web-audio-api</a></p>
<p><a target="_blank" href="http://webcache.googleusercontent.com/search?q=cache:z61Zyg6KmcYJ:https://dvcs.w3.org/hg/audio/raw-file/tip/webaudio/specification.html+&cd=1&hl=en&ct=clnk&gl=uk&client=firefox-a">http://webcache.googleusercontent.com/search?q=cache:z61Zyg6KmcYJ:https://dvcs.w3.org/hg/audio/raw-file/tip/webaudio/specification.html+&cd=1&hl=en&ct=clnk&gl=uk&client=firefox-a</a></p>
<h5>To to</h5>
<ul>
  <li>UI for adding tracks</li>
  <li>UI for altering frequency on each beat</li>
  <li>Ensure overlapping notes play OK</li>
  <li>Track gain (new node &amp; ui)</li>
  <li>Server side back-end</li>
</ul>